# Expected output of:
#   crossplane render --include-full-xr yaml/xr-valid.yaml yaml/composition.yaml yaml/functions.yaml \
#     --xrd=yaml/xrd.yaml --required-resources=yaml/required/envcfg-valid.yaml
---
apiVersion: example.com/v1alpha1
kind: IAMUser
metadata:
  name: developer-alice
  namespace: default
spec:
  createAccessKey: true
  policyArns:
    - arn:aws:iam::aws:policy/ReadOnlyAccess
    - arn:aws:iam::aws:policy/PowerUserAccess
  team: engineering
  username: alice-developer
status:
  accessKey:
    id: pending
    ready: false
    secretRef:
      name: alice-developer-credentials
      namespace: default
    synced: false
  conditions:
    - reason: Creating
      status: "False"
      type: Ready
  policyAttachments:
    ready: 0
    synced: 0
    total: 2
  user:
    arn: pending
    id: pending
    ready: false
    synced: false
---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: User
metadata:
  annotations:
    crossplane.io/composition-resource-name: iam-user
  labels:
    crossplane.io/composite: developer-alice
  name: alice-developer
  namespace: default
  ownerReferences:
    - apiVersion: example.com/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: IAMUser
      name: developer-alice
spec:
  forProvider:
    tags:
      Environment: dev
      ManagedBy: crossplane
      Name: alice-developer
      Team: engineering
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
