# Expected output of:
#   crossplane render --include-full-xr yaml/xr-valid.yaml yaml/composition.yaml yaml/functions.yaml \
#     --xrd=yaml/xrd.yaml --required-resources=yaml/required/envcfg-valid.yaml --observed-resources=yaml/observed/ready
---
apiVersion: example.com/v1alpha1
kind: IAMUser
metadata:
  name: developer-alice
  namespace: default
spec:
  createAccessKey: true
  policyArns:
    - arn:aws:iam::aws:policy/ReadOnlyAccess
    - arn:aws:iam::aws:policy/PowerUserAccess
  team: engineering
  username: alice-developer
status:
  accessKey:
    id: AKIAIOSFODNN7EXAMPLE
    ready: true
    secretRef:
      name: alice-developer-credentials
      namespace: default
    synced: true
  conditions:
    - reason: Available
      status: "True"
      type: Ready
  policyAttachments:
    ready: 2
    synced: 2
    total: 2
  user:
    arn: arn:aws:iam::000000000000:user/alice-developer
    id: alice-developer
    ready: true
    synced: true
---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: AccessKey
metadata:
  annotations:
    crossplane.io/composition-resource-name: access-key
  labels:
    crossplane.io/composite: developer-alice
  name: alice-developer-key
  namespace: default
  ownerReferences:
    - apiVersion: example.com/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: IAMUser
      name: developer-alice
spec:
  forProvider:
    user: alice-developer
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
  writeConnectionSecretToRef:
    name: alice-developer-credentials
---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: User
metadata:
  annotations:
    crossplane.io/composition-resource-name: iam-user
  labels:
    crossplane.io/composite: developer-alice
  name: alice-developer
  namespace: default
  ownerReferences:
    - apiVersion: example.com/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: IAMUser
      name: developer-alice
spec:
  forProvider:
    tags:
      Environment: dev
      ManagedBy: crossplane
      Name: alice-developer
      Team: engineering
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: UserPolicyAttachment
metadata:
  annotations:
    crossplane.io/composition-resource-name: policy-attachment-0
  labels:
    crossplane.io/composite: developer-alice
  name: alice-developer-policy-0
  namespace: default
  ownerReferences:
    - apiVersion: example.com/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: IAMUser
      name: developer-alice
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/ReadOnlyAccess
    user: alice-developer
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: UserPolicyAttachment
metadata:
  annotations:
    crossplane.io/composition-resource-name: policy-attachment-1
  labels:
    crossplane.io/composite: developer-alice
  name: alice-developer-policy-1
  namespace: default
  ownerReferences:
    - apiVersion: example.com/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: IAMUser
      name: developer-alice
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/PowerUserAccess
    user: alice-developer
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
