apiVersion: apps/v1
kind: Deployment
metadata:
  name: defaults-nginx
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: defaults
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
      app.kubernetes.io/instance: defaults
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
        app.kubernetes.io/instance: defaults
    spec:
      serviceAccountName: defaults-nginx
      containers:
        - name: nginx
          image: "nginx:1.16.0"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
