apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: website
spec:
  components:
    - name: frontend
      type: webservice
      properties:
        image: oamdev/testapp:v1
        port: ($port) # Templated for reuse between test cases
      traits:
        - type: gateway
          properties:
            domain: localhost
            http:
              "/": ($port) # Templated for reuse between test cases
