apiVersion: example.com/v1alpha1
kind: IAMUser
metadata:
  name: developer-alice
  namespace: default
spec:
  username: alice-developer
  createAccessKey: true
  team: engineering
  policyArns:
    - arn:aws:iam::aws:policy/ReadOnlyAccess
    - arn:aws:iam::aws:policy/PowerUserAccess
