name: Run tests and upload coverage

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Run tests and upload coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Install k3d
        run: curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

      - name: Install vela
        run: curl -fsSL https://kubevela.io/script/install.sh | bash

      - name: Install crossplane
        run: |
          curl -sfL "https://cli.crossplane.io/install.sh" | sh
          sudo mv crossplane /usr/local/bin

      - name: Run tests
        run: make test-all

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
